
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

spring.application.name=backend
server.port=8080
# Base de données PostgreSQL (valeurs lues depuis le fichier .env)
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.output.ansi.enabled=ALWAYS

# Base de données PostgreSQL (valeurs lues depuis le fichier .env)
spring.datasource.driver-class-name=org.postgresql.Driver

# Activation de la génération de la spécification OpenAPI 3.1
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=OPENAPI_3_1
# Chemin vers la documentation en ligne
# TODO désactiver ça pour la production
springdoc.swagger-ui.path=/swagger-ui.html

# Configuration concernant la gestion ds JWT
jwt.secret=change-moi-avec-une-longue-chaine-secrete-aleatoire-en-production
jwt-expiration=86400000

# Base de données PostgreSQL (doit correspondre à docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/symphonia
spring.datasource.username=symphonia
spring.datasource.password=symphonia

# Configuration des emails (meilpit local)
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Configuration des CORS (à adapter en fonction de l'environnement)
# app.cors.origin=http://localhost:3000
app.cors.origin=*
