spring.config.import=optional:file:.env.properties

spring.application.name=backend
server.port=8081

# Désactivation des options pour génération de la documentation API
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Base de données PostgreSQL (valeurs lues depuis le fichier .env)
spring.datasource.driver-class-name=org.postgresql.Driver
