# Chargement d'un fichier de configuration externe propre au développement
spring.config.import=optional:file:.env.properties

spring.application.name=backend
server.port=8080
# Base de données PostgreSQL (valeurs lues depuis le fichier .env)
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.output.ansi.enabled=ALWAYS

# Base de données PostgreSQL (valeurs lues depuis le fichier .env)
spring.datasource.driver-class-name=org.postgresql.Driver

# Activation de la génération de la spécification OpenAPI 3.1
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=OPENAPI_3_1
# Chemin vers la documentation en ligne
# TODO désactiver ça pour la production
springdoc.swagger-ui.path=/swagger-ui.html
