spring.config.import=optional:file:.env.properties

server.port=8080

# Base de données PostgreSQL (valeurs lues depuis le fichier .env)
spring.datasource.driver-class-name=org.postgresql.Driver
# Ajout di dialect pour communication avec l'éléphant PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.username=symphonia
spring.datasource.password=symphonia

jwt.secret=change-moi-avec-une-longue-chaine-secrete-aleatoire-en-production
jwt.expiration-ms=86400000

# Emails (Mailpit en local)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# CORS : origine autorisée pour le frontend
app.cors.origin=http://localhost:3000
