spring.application.name=backend
server.port=8081

# Désactivation des options pour génération de la documentation API
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Base de données PostgreSQL (valeurs lues depuis le fichier .env)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration concernant la gestion ds JWT
jwt.secret=change-moi-avec-une-longue-chaine-secrete-aleatoire-en-production
jwt-expiration=86400000

# Base de données PostgreSQL (doit correspondre à docker-compose.yml)
spring.datasource.url=jdbc:postgresql://postgres:5432/symphonia
spring.datasource.username=symphonia
spring.datasource.password=symphonia

# Configuration des emails (meilpit local)
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Configuration des CORS (à adapter en fonction de l'environnement)
# app.cors.origin=http://localhost:3000
app.cors.origin=*
